start cmd /c c_server.exe
start cmd /c c_server.exe
start cmd /c c_server.exe
start cmd /c c_server.exe
start cmd /c c_server.exe
start cmd /c c_server.exe
start cmd /c c_server.exe
start cmd /c c_server.exe
start cmd /c c_server.exe
